---
- name: "Create directory for installation"
  file:
    path: "{{ installation_path }}"
    state: directory

- name: "Retrieve apache flink archive"
  get_url:
    url: "{{ apache_flink_url }}"
    dest: "{{ installation_path }}"
    timeout: 600

- name: "Unarchive apache flink archive"
  unarchive:
    src: "{{ installation_path }}/flink-{{ apache_flink_version }}-bin-scala_2.11.tgz"
    dest: "{{ installation_path }}"
    owner: root
    group: root
    remote_src: yes

- name: "Remove configuration files"
  file:
    path: "{{ installation_path }}/flink-{{ apache_flink_version }}/conf/{{ item }}"
    state: absent
  with_items:
    - masters
    - slaves

- name: "Re-create and set job managers in configuration file"
  lineinfile:
    create: yes
    state: present
    dest: "{{ installation_path }}/flink-{{ apache_flink_version }}/conf/masters"
    line: "{{ item }}:8081"
  with_items:
    - "{{ hostvars[inventory_hostname].groups.FlinkJobManager }}"

- name: "Re-create and set task managers in configuration file"
  lineinfile:
    create: yes
    state: present
    dest: "{{ installation_path }}/flink-{{ apache_flink_version }}/conf/slaves"
    line: "{{ item }}"
  with_items:
    - "{{ hostvars[inventory_hostname].groups.FlinkTaskManager }}"

- name: "Set main job manager hostname in configuration file"
  lineinfile:
    dest: "{{ installation_path }}/flink-{{ apache_flink_version }}/conf/flink-conf.yaml"
    regexp: '^jobmanager.rpc.address:\s'
    line: 'jobmanager.rpc.address: {{ hostvars[inventory_hostname].groups.FlinkJobManager[0] }}'
    state: present

- name: "Set task slots available for each task manager"
  lineinfile:
    dest: "{{ installation_path }}/flink-{{ apache_flink_version }}/conf/flink-conf.yaml"
    regexp: '^taskmanager.numberOfTaskSlots:\s'
    line: 'taskmanager.numberOfTaskSlots: {{ nb_task_manager_slots }}'
    state: present

- name: "Remove apache flink archive"
  file:
    path: "{{ installation_path }}/flink-{{ apache_flink_version }}-bin-scala_2.11.tgz"
    state: absent
